version: '3.1'
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    # Copia o arquivo prometheus.yml para dentro do container
    volumes:
    - "./src/main/resources/prometheus.yml:/etc/prometheus/prometheus.yml"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"